import React,{useState,useEffect} from 'react';
import {api} from './api';
import {LeadBrief} from './offers';
import {offerNames} from '../../site/offers.mjs';
const date=s=>new Date(s.includes('T')?s:s+'Z').toLocaleString('ru-RU');
const labels={new:'Новая',inwork:'В работе',done:'Завершена',rejected:'Отклонена'};
const deliveryLabels={pending:'В очереди',retry:'Повторная попытка',sent:'Отправлено',failed:'Ошибка'};

export function Leads({admin,run,notify,ask}){
 const [rows,setRows]=useState([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[filter,setFilter]=useState(''),[search,setSearch]=useState(''),[detail,setDetail]=useState(null),[users,setUsers]=useState([]),[note,setNote]=useState(''),[loaded,setLoaded]=useState(false);
 const load=async()=>{const r=await api('/admin/leads?'+new URLSearchParams({status:filter,search,offset}));setRows(r.leads);setTotal(r.total);setLoaded(true);};
 const open=async id=>{setDetail(await api('/admin/leads/'+id));setNote('');};
 useEffect(()=>{run(async()=>{await load();const r=await api('/admin/users');setUsers(r.users);});},[filter,offset]);
 const update=async body=>{await api('/admin/leads/'+detail.lead.id,'PATCH',{status:detail.lead.status,assignee:detail.lead.assignee,...body});await open(detail.lead.id);await load();notify('Заявка обновлена');};
 return <><div className="toolbar"><label>Статус<select value={filter} onChange={e=>{setFilter(e.target.value);setOffset(0);}}><option value="">Все заявки</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><form className="inline" onSubmit={e=>{e.preventDefault();setOffset(0);run(load);}}><label>Имя или телефон<input value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="secondary">Найти</button></form><button className="secondary" onClick={()=>run(load)}>Обновить</button></div><div className="card"><div className="section-title"><h2>Обращения с сайта</h2><span className="badge">Всего: {total}</span></div>{!loaded?<p>Загружаем заявки…</p>:!rows.length?<div className="empty"><h3>Заявок пока нет</h3><p>После отправки формы обращение появится здесь. Демонстрационных заявок в рабочей базе нет.</p></div>:<div className="table-wrap"><table><thead><tr><th>Номер / дата</th><th>Клиент</th><th>Страница</th><th>Статус</th><th/></tr></thead><tbody>{rows.map(l=><tr key={l.id}><td>#{l.id}<small>{date(l.created_at)}</small></td><td>{l.name||'Без имени'}<small>{l.phone}</small></td><td>{l.source}</td><td><span className={'badge '+(l.status==='done'?'good':'')}>{labels[l.status]}</span></td><td><button className="secondary" onClick={()=>run(()=>open(l.id))}>Открыть</button></td></tr>)}</tbody></table></div>}<div className="pagination"><button className="secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>← Назад</button><span>{offset+1}–{Math.min(offset+rows.length,total)} из {total}</span><button className="secondary" disabled={offset+100>=total} onClick={()=>setOffset(offset+100)}>Далее →</button></div></div>
 {detail&&<section className="card"><div className="section-title"><h2>Заявка #{detail.lead.id}</h2><button className="quiet" onClick={()=>setDetail(null)}>Закрыть ×</button></div><div className="columns"><div><dl><dt>Имя</dt><dd>{detail.lead.name||'Не указано'}</dd><dt>Телефон</dt><dd><a href={'tel:'+detail.lead.phone}>{detail.lead.phone}</a></dd><dt>Выбранная услуга</dt><dd>{offerNames[detail.lead.offer]||'Обсуждение задачи'}</dd><dt>Комментарий</dt><dd className="pre-wrap">{detail.lead.comment||'Не указан'}</dd><dt>Источник</dt><dd>{detail.lead.source}</dd><dt>UTM</dt><dd>{Object.entries(JSON.parse(detail.lead.utm)).map(([k,v])=><div key={k}>{k}: {v}</div>)}</dd><dt>Версия согласия</dt><dd>{detail.lead.consent_version}</dd></dl></div><div><label>Статус<select value={detail.lead.status} onChange={e=>run(()=>update({status:e.target.value}))}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Ответственный<select value={detail.lead.assignee||''} onChange={e=>run(()=>update({assignee:e.target.value?Number(e.target.value):null}))}><option value="">Не назначен</option>{users.map(u=><option key={u.id} value={u.id}>{u.login}</option>)}</select></label><h3>Доставка уведомлений</h3>{detail.deliveries.length?detail.deliveries.map(d=><p key={d.id}>{d.channel}: <strong>{deliveryLabels[d.status]}</strong><small>Попыток: {d.attempts}. {d.last_error||''}</small></p>):<p className="muted">Каналы не были подключены при получении заявки. Обращение сохранено в базе.</p>}{admin&&detail.deliveries.some(d=>d.status==='failed')&&<button className="secondary" onClick={()=>run(async()=>{await api('/admin/leads/'+detail.lead.id+'/retry','POST',{});await open(detail.lead.id);notify('Уведомления поставлены на повторную доставку');})}>Повторить доставку</button>}</div></div><LeadBrief lead={detail.lead} run={run} notify={notify}/><h3>Заметки</h3>{detail.notes.map(n=><div className="note" key={n.id}><strong>{n.actor} · {date(n.created_at)}</strong><p className="pre-wrap">{n.text}</p></div>)}<form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/admin/leads/'+detail.lead.id+'/notes','POST',{text:note});await open(detail.lead.id);});}}><label>Добавить заметку<textarea rows="3" value={note} maxLength="3000" onChange={e=>setNote(e.target.value)} required/></label><button disabled={!note.trim()}>Сохранить заметку</button></form>{admin&&<button className="danger" onClick={()=>ask({title:'Удалить заявку?',text:'Контакты, заметки и история доставки этой заявки будут удалены без возможности восстановления в админке.',action:()=>run(async()=>{await api('/admin/leads/'+detail.lead.id,'DELETE',{});setDetail(null);await load();notify('Заявка удалена');})})}>Удалить заявку</button>}</section>}</>;
}

export function Media({run,notify,admin,ask}){
 const [items,setItems]=useState([]),[uploading,setUploading]=useState(false);
 const load=async()=>setItems((await api('/admin/media')).media);useEffect(()=>{run(load);},[]);
 return <div className="card"><div className="section-title"><h2>Фотографии для страниц</h2><label className="upload button">{uploading?'Загружаем…':'Загрузить фото'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>{const file=e.target.files[0];if(!file)return;run(async()=>{setUploading(true);try{const data=new FormData();data.append('file',file);await api('/admin/media','POST',data);await load();notify('Фотография загружена. Выберите её в изображениях нужной страницы.');}finally{setUploading(false);e.target.value='';}});}}/></label></div><p>JPG, PNG или WebP до 10 МБ. Фотографии оптимизируются для сайта. Логотип остаётся исходным.</p>{!items.length?<div className="empty"><h3>Новых фотографий пока нет</h3><p>Исходные изображения сохранены и доступны в редакторе страниц.</p></div>:<div className="image-grid">{items.map(m=><div className="image-slot" key={m.id}><img src={m.url} alt={m.original_name}/><strong>{m.original_name}</strong><small>{m.width} × {m.height} · {Math.round(m.bytes/1024)} КБ</small><a href={m.url} target="_blank" rel="noopener">Открыть изображение ↗</a>{admin&&<button className="quiet" onClick={()=>ask({title:'Удалить фотографию?',text:'Удаление доступно только для фотографий, не используемых в черновике, опубликованном сайте и истории версий.',action:()=>run(async()=>{await api('/admin/media/'+m.id,'DELETE',{});await load();notify('Неиспользуемая фотография удалена');})})}>Удалить</button>}</div>)}</div>}</div>;
}

export function Integrations({run,notify}){
 const [settings,setSettings]=useState(null);useEffect(()=>{run(async()=>setSettings((await api('/admin/settings/integrations')).settings));},[]);
 if(!settings)return <p>Загружаем настройки…</p>;
 const update=(channel,key,value)=>setSettings(s=>({...s,[channel]:{...s[channel],[key]:value}}));
 const field=(channel,key,label,secret=false)=><label key={key}>{label}<input type={secret?'password':'text'} autoComplete="off" value={settings[channel][key]||''} placeholder={settings[channel][key+'Configured']?'Сохранено. Оставьте пустым, чтобы не менять':''} onChange={e=>update(channel,key,e.target.value)}/></label>;
 return <form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/admin/settings/integrations','PUT',settings);setSettings((await api('/admin/settings/integrations')).settings);notify('Настройки каналов сохранены');});}}><div className="notice">Заявка сначала сохраняется в админке. Подключённые каналы получают уведомления независимо; ошибки доставки видны в карточке заявки.</div><div className="card"><h2>Telegram</h2><label className="checkbox"><input type="checkbox" checked={settings.telegram.enabled} onChange={e=>update('telegram','enabled',e.target.checked)}/>Отправлять новые заявки в чат</label>{field('telegram','token','Токен бота',true)}{field('telegram','chatId','ID чата')}</div><div className="card"><h2>Bitrix24</h2><label className="checkbox"><input type="checkbox" checked={settings.bitrix.enabled} onChange={e=>update('bitrix','enabled',e.target.checked)}/>Создавать лиды</label>{field('bitrix','url','Адрес входящего вебхука',true)}<small>Формат: https://ваш-портал.bitrix24.ru/rest/ID/КЛЮЧ/</small></div><div className="card"><h2>Email</h2><label className="checkbox"><input type="checkbox" checked={settings.email.enabled} onChange={e=>update('email','enabled',e.target.checked)}/>Отправлять уведомления по почте</label>{field('email','host','SMTP-сервер')}<label>Порт<select value={settings.email.port} onChange={e=>{update('email','port',Number(e.target.value));update('email','secure',e.target.value==='465');}}><option value="465">465 · TLS</option><option value="587">587 · STARTTLS</option></select></label>{field('email','user','Логин SMTP')}{field('email','password','Пароль SMTP',true)}{field('email','from','Адрес отправителя')}{field('email','to','Адрес получателя')}</div><button>Сохранить каналы</button><p className="muted">Эти настройки применяются сразу. Проверка реальной доставки выполняется после подключения каналов; автоматические тестовые сообщения не отправляются.</p></form>;
}

export function Users({admin,current,run,notify,ask}){
 const [users,setUsers]=useState([]),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('manager'),[oldPassword,setOld]=useState(''),[newPassword,setNew]=useState('');
 const load=async()=>setUsers((await api('/admin/users')).users);useEffect(()=>{run(load);},[]);
 return <>{admin&&<><div className="card"><h2>Доступ к сайту</h2><div className="table-wrap"><table><thead><tr><th>Пользователь</th><th>Роль</th><th>Доступ</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.login}{u.id===current.id?' (вы)':''}</td><td>{u.role==='admin'?'Администратор':'Менеджер'}</td><td>{u.active?'Активен':'Отключён'}</td><td>{u.id!==current.id&&<button className="secondary" onClick={()=>ask({title:u.active?'Отключить доступ?':'Включить доступ?',text:'Текущие сессии пользователя будут завершены.',action:()=>run(async()=>{await api('/admin/users/'+u.id,'PATCH',{active:!u.active,role:u.role});await load();notify('Доступ обновлён');})})}>{u.active?'Отключить':'Включить'}</button>}</td></tr>)}</tbody></table></div><p className="muted">Менеджер работает с заявками, фотографиями и черновиками. Публикация, удаление и настройки доступа разрешены администратору.</p></div><form className="card" onSubmit={e=>{e.preventDefault();run(async()=>{await api('/admin/users','POST',{login,password,role});setLogin('');setPassword('');await load();notify('Пользователь создан');});}}><h2>Добавить пользователя</h2><label>Логин<input value={login} autoComplete="off" required pattern="[a-zA-Z0-9_.-]{3,50}" onChange={e=>setLogin(e.target.value)}/></label><label>Пароль · минимум 12 символов<input type="password" autoComplete="new-password" minLength="12" required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Роль<select value={role} onChange={e=>setRole(e.target.value)}><option value="manager">Менеджер</option><option value="admin">Администратор</option></select></label><button>Создать пользователя</button></form></>}
 <form className="card" onSubmit={e=>{e.preventDefault();run(async()=>{await api('/auth/password','POST',{currentPassword:oldPassword,newPassword});setOld('');setNew('');notify('Пароль изменён. Другие сессии завершены.');});}}><h2>Изменить свой пароль</h2><label>Текущий пароль<input type="password" autoComplete="current-password" value={oldPassword} onChange={e=>setOld(e.target.value)} required/></label><label>Новый пароль<input type="password" autoComplete="new-password" minLength="12" value={newPassword} onChange={e=>setNew(e.target.value)} required/></label><button>Изменить пароль</button></form></>;
}

export function History({admin,run,notify,revision,reload,ask,dirty}){
 const [versions,setVersions]=useState([]);const load=async()=>setVersions((await api('/admin/content/versions')).versions);useEffect(()=>{run(load);},[revision]);
 return <div className="card"><h2>История публикаций</h2><p>Восстановление переносит выбранную версию в черновик. Сначала проверьте её, затем опубликуйте.</p>{dirty&&<div className="notice">Есть несохранённые изменения. Восстановление версии заменит их.</div>}<div className="table-wrap"><table><thead><tr><th>Версия</th><th>Дата</th><th>Автор</th><th>Комментарий</th><th/></tr></thead><tbody>{versions.map(v=><tr key={v.id}><td>#{v.id}</td><td>{date(v.created_at)}</td><td>{v.actor}</td><td>{v.note}</td><td>{admin&&<button className="secondary" onClick={()=>ask({title:`Восстановить версию ${v.id}?`,text:'Текущий черновик будет заменён содержимым этой версии. Публичная версия пока не изменится.',action:()=>run(async()=>{const r=await api('/admin/content/versions/'+v.id+'/restore','POST',{revision});await reload();await load();notify(r.message);})})}>В черновик</button>}</td></tr>)}</tbody></table></div>{admin&&<button className="danger" onClick={()=>ask({title:'Отменить изменения черновика?',text:'Черновик будет возвращён к текущей опубликованной версии.',action:()=>run(async()=>{await api('/admin/content/discard','POST',{revision});await reload();notify('Черновик возвращён к опубликованной версии');})})}>Отменить изменения черновика</button>}</div>;
}
export function Audit({run}){
 const [events,setEvents]=useState([]);useEffect(()=>{run(async()=>setEvents((await api('/admin/audit')).events));},[]);
 const names={'login':'Вход','login.failed':'Неудачный вход','draft.saved':'Сохранение черновика','draft.discarded':'Отмена черновика','content.published':'Публикация','version.restored.to.draft':'Восстановление в черновик','password.changed':'Смена пароля','media.uploaded':'Загрузка фото','media.deleted':'Удаление фото','lead.updated':'Изменение заявки','lead.brief.updated':'Уточнение задачи','content.migrated':'Обновление модели контента','lead.deleted':'Удаление заявки','integrations.updated':'Настройка каналов','user.created':'Создание пользователя','user.updated':'Изменение доступа','delivery.retry':'Повтор доставки'};
 return <div className="card"><h2>Последние действия</h2><div className="table-wrap"><table><thead><tr><th>Дата</th><th>Пользователь</th><th>Действие</th><th>Детали</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{date(e.created_at)}</td><td>{e.actor}</td><td>{names[e.action]||e.action}</td><td><code>{e.details==='{}'?'—':e.details}</code></td></tr>)}</tbody></table></div></div>;
}
