import React,{useState} from 'react';
import research from '../../site/seo-research.json';

export function SeoResearch({download}){
 const [a,setA]=useState('resale'),[b,setB]=useState('resale_variant');
 const sampleA=research.serp.samples.find(s=>s.id===a),sampleB=research.serp.samples.find(s=>s.id===b);
 const pair=research.serp.pairs.find(p=>p.a===a&&p.b===b||p.a===b&&p.b===a);
 const select=(label,value,set)=><label>{label}<select value={value} onChange={e=>set(e.target.value)}>{research.serp.samples.map(s=><option key={s.id} value={s.id}>{s.query}</option>)}</select></label>;
 const list=s=><div><h3>{s.query}</h3><p>{s.sources.map((url,i)=><React.Fragment key={url}>{i>0?' · ':''}<a href={url} target="_blank" rel="noopener noreferrer">Поиск: страница {i+1}</a></React.Fragment>)}</p><ol>{s.urls.map(url=><li key={url} style={{overflowWrap:'anywhere'}}><a href={url} target="_blank" rel="noopener noreferrer">{decodeURI(url)}</a></li>)}</ol></div>;
 return <>
  <div className="card"><h2>Исследование выдачи · 08.09.2026</h2><p>Сохранённый снимок исследования: {research.wordstat.measurements.length} измерения Wordstat, {research.serp.samples.length} поисковых выборок, {research.serp.pairs.length} сравнений. Редактируемые значения находятся во вкладке «Запросы и частотность»; здесь сохранены исходные данные проверки.</p><button className="secondary" onClick={()=>download('seo-research-2026-09-08.json',JSON.stringify(research,null,2))}>Скачать исследование JSON</button><details><summary>Методика и ограничения</summary>{research.methodology.map(t=><p key={t}>{t}</p>)}<p><a href="https://yandex.ru/support2/wordstat/ru/content/operators" target="_blank" rel="noopener noreferrer">Операторы Wordstat</a> · <a href="https://yandex.cloud/docs/search-api/reference/regions" target="_blank" rel="noopener noreferrer">Регионы Яндекса</a></p></details></div>
  <div className="card"><h2>Сравнить две формулировки</h2><div className="seo-grid">{select('Первый запрос',a,setA)}{select('Второй запрос',b,setB)}</div>{a===b?<p role="status">Выберите два разных запроса.</p>:<><p role="status"><strong>{pair.urlOverlap} из 10 общих URL ({pair.percent}%)</strong> · общих сайтов: {pair.hostOverlap}. Совпадение сайта с разными страницами не означает совпадения URL.</p><p className="muted">Списки ниже сохранены 8 сентября. Ссылки на поиск откроют сегодняшнюю выдачу; она может отличаться. Реклама и виджеты исключены, обычные результаты каталогов и карт включены.</p><details><summary>Посмотреть обе десятки URL</summary><div className="seo-grid">{list(sampleA)}{list(sampleB)}</div></details>{pair.commonUrls.length>0&&<details><summary>Общие URL</summary><ul>{pair.commonUrls.map(url=><li key={url} style={{overflowWrap:'anywhere'}}><a href={url} target="_blank" rel="noopener noreferrer">{decodeURI(url)}</a></li>)}</ul></details>}</>}</div>
  <div className="card"><h2>Решения по структуре</h2><p>Решения учитывают выдачу, задачу посетителя и состав услуги. Низкое пересечение само по себе не требует новой страницы.</p>{research.decisions.map(d=><details className="seo-query" key={d.a+'-'+d.b}><summary>{d.action}</summary><p>{d.paths.join(' · ')} · {d.overlap}/10 общих URL</p><p>{d.reason}</p></details>)}</div>
 </>;
}
